### ISSUE TITLE
Mitos2012/ImageSets/ don't have train.txt ?

### ISSUE THREAD

**Issue by LIYHUI** [ChaoLi977/DeepMitosis#5]
when I run  .`/experiments/scripts/faster_rcnn_end2end_12.sh 0 VGG_CNN_M_1024_Scale mitos --set EXP_DIR XX
`there is an error :

> E0227 10:01:53.012403 16492 common.cpp:104] Cannot create Cublas handle. Cublas won't be available.
> E0227 10:01:53.298936 16492 common.cpp:111] Cannot create Curand generator. Curand won't be available.
> E0227 10:01:53.299005 16492 common.cpp:131] Curand not available. Skipping setting the curand seed.
> Traceback (most recent call last):
>   File "./tools/train_net.py", line 104, in <module>
>     imdb, roidb = combined_roidb(args.imdb_name)
>   File "./tools/train_net.py", line 69, in combined_roidb
>     roidbs = [get_roidb(s) for s in imdb_names.split('+')]
>   File "./tools/train_net.py", line 62, in get_roidb
>     imdb = get_imdb(imdb_name)
>   File "/home/lyh/mitosis_DET/DeepMitosis/DeepDetection/tools/../lib/datasets/factory.py", line 51, in get_imdb
>     return __sets[name]()
>   File "/home/lyh/mitosis_DET/DeepMitosis/DeepDetection/tools/../lib/datasets/factory.py", line 40, in <lambda>
>     __sets[name] = (lambda split=split, year=year: mitos(split, year))
>   File "/home/lyh/mitosis_DET/DeepMitosis/DeepDetection/tools/../lib/datasets/mitos.py", line 34, in __init__
>     self._image_index = self._load_image_set_index()
>   File "/home/lyh/mitosis_DET/DeepMitosis/DeepDetection/tools/../lib/datasets/mitos.py", line 80, in _load_image_set_index
>     'Path does not exist: {}'.format(image_set_file)
> AssertionError: Path does not exist: /home/lyh/mitosis_DET/DeepMitosis/DeepDetection/data/Mitos2012/ImageSets/train.txt
> 

can you give it? and why"Cannot create Cublas handle. Cublas won't be available." thank you very mucn!

**Comment by ChaoLi977** [comment]
Sorry, the training list file is lost since the project was done about six years ago, but you can prepare the training images as the description of our paper.

**Comment by LIYHUI** [comment]
Thanks for your reply~
